### ISSUE TITLE
syslog logs not in json format

### ISSUE THREAD

**Issue by jurgob** [joyent/node-bunyan-syslog#43]
Hi, if I use this module, my syslog is not in json format.
Ive thee timestamp and then the json sended
If I log {"name":"test"} I have:

`Mar 28 10:54:49 machine_name my_tag: {"name":"test"}`

is it the expected behavior? should I configure the syslog? 
In this case, it would be nice the mention those problem in the README page

**Comment by abramz** [comment]
This behavior is expected.

https://tools.ietf.org/html/rfc5424

**Comment by melloc** [comment]
@jurgob This is the default behaviour when logging. If you're using `rsyslog`, you can use templates/property replacers to get just the JSON. I've updated the [README](https://github.com/joyent/node-bunyan-syslog/blob/master/README.md) to describe how to do this.
