### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by mpodlasin** [joyent/node-bunyan-syslog#44]
Hi. 

Last release was in 2015. On master there are changes that make this project usable for us. Any chances for a release?

**Comment by damon-at-sportsbet** [comment]
I published a package of the latest version of this until the maintainer comes back:
https://github.com/sportsbet/node-bunyan-syslog

**Comment by sgmeyer** [comment]
Yes, it seems that way.  There is a known issue with node 6+.  There was a fix for this merged a while back, but the maintainer never had a chance to publish to npm.  Hopeful this will comeback or allow a transfer to a new maintainer.

**Comment by melloc** [comment]
I've published `bunyan-syslog@0.3.2`, which supports node v6+.
