### ISSUE TITLE
README example not correct

### ISSUE THREAD

**Issue by saitheexplorer** [joyent/node-bunyan-syslog#9]
On line 21, it has `facility: bsyslog.local0`.

Should that be `facility: bsyslog.facility.local0`?

**Comment by melloc** [comment]
All of the facilities are available on both the module, and on the `facility` object. See [here](https://github.com/joyent/node-bunyan-syslog/blob/c3daebfdf49f737110616a87f52c1a0feb6fdbd9/lib/index.js#L68-L70).
